services:
  avito-shop:
    build:
      context: .
    restart: no
    ports:
      - "8080:8080"
    volumes:
    - ./configs/:/data/
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=avito2025
      - POSTGRES_DB=avito_shop
    depends_on:
      postgres_avito_shop:
        condition: service_healthy
    networks:
      - internal
  postgres_avito_shop:
    image: postgres:15
    volumes:
      - postgres_avito_shop:/var/lib/postgresql/data/
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=avito2025
      - POSTGRES_DB=avito_shop
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U db_admin -d avito_shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

volumes:
  postgres_avito_shop:
networks:
  internal: